export const blogs = [
  {
    id: 1,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Exploring User Behavior: Understanding and Influencing it",
    date: "November 27, 2024",
    hashtags: ["ux design"],
  },
  {
    id: 2,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Insights into Dark UX Practices: What to Watch For",
    date: "November 25, 2024",
    hashtags: ["ux design"],
  },
  {
    id: 3,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "User Experience Design Services by Gapsy Studio",
    date: "November 18, 2024",
    hashtags: ["ux design"],
  },
  {
    id: 4,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Best Practices for Banking App UX in 2024",
    date: "November 18, 2024",
    hashtags: ["ux design", "app design"],
  },
  {
    id: 5,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Fintech UX Design Trends for 2024",
    date: "November 4, 2024",
    hashtags: ["ux design", "fintech", "trends"],
  },
  {
    id: 6,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Nora Case Study: Nourishing the Workplace",
    date: "November 1, 2024",
    hashtags: ["ux design", "ui design"],
  },
  {
    id: 7,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Innovative Design Approaches: Creating Conversational User Interfaces",
    date: "October 18, 2024",
    hashtags: ["ui design"],
  },
  {
    id: 8,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Mastering Happy Path UX: A Guide to Delightful User Experiences",
    date: "October 17, 2024",
    hashtags: ["ux design"],
  },
  {
    id: 9,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Designing Accessible E-commerce Platforms for All Users",
    date: "October 10, 2024",
    hashtags: ["e-commerce", "ux design"],
  },
  {
    id: 10,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Emerging SaaS UX Trends to Watch in 2024",
    date: "October 7, 2024",
    hashtags: ["saas", "trends"],
  },
  {
    id: 11,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "How Typography Affects User Retention Rates",
    date: "September 25, 2024",
    hashtags: ["typography", "ux design"],
  },
  {
    id: 12,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Exploring Minimalist UI Design for Modern Web Apps",
    date: "September 20, 2024",
    hashtags: ["ui design", "web design"],
  },
  {
    id: 13,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Top 5 Product Design Strategies for Startups",
    date: "September 15, 2024",
    hashtags: ["product design", "startups"],
  },
  {
    id: 14,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "The Future of Branding: Staying Relevant in 2024",
    date: "September 12, 2024",
    hashtags: ["branding", "trends"],
  },
  {
    id: 15,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Outsourcing Web Development: The Do's and Don'ts",
    date: "September 8, 2024",
    hashtags: ["outsourcing", "web development"],
  },
  {
    id: 16,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "UX in Real Estate: How Design Drives Sales",
    date: "August 30, 2024",
    hashtags: ["ux design", "real estate"],
  },
  {
    id: 17,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Healthcare App Design: Meeting the Needs of Users",
    date: "August 20, 2024",
    hashtags: ["healthcare", "app design"],
  },
  {
    id: 18,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Betting Apps UX: Balancing Engagement and Ethics",
    date: "August 10, 2024",
    hashtags: ["betting", "ux design"],
  },
  {
    id: 19,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "Education Platforms: UX Best Practices for Online Learning",
    date: "August 5, 2024",
    hashtags: ["education", "ux design"],
  },
  {
    id: 20,
    image: '/images/blogs/article-elit-web-user-experience-design-services-cover.jpg',
    title: "How Agile Development Enhances UX Processes",
    date: "July 30, 2024",
    hashtags: ["agile", "ux design"],
  },
];
